units:
  # Proxy Spacing Variables
  # cx = 18, cy = 17
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 5
  py: ky + 5
  # Double padding for case
  dpx: kx + 9
  dpy: ky + 9
  # Smaller padding for pcb stand
  spx: kx + 3
  spy: ky + 3


  case_bottom_thick: 2
  pcb_height: 1.5

  # 1.5 (radius) <=> 3mm (diameter) 
  # (2mm for M2 screw + 0.7 mm for screw insert) 
  screw_rad: 1.35 
  screw_standoff_rad: 2.5

  # screw insert are 3 milimeters height
  pcb_bottom_height: case_bottom_thick + 5

  # this way the wall should be at the same level what pcb is 
  case_wall_height: pcb_bottom_height + pcb_height + 0

  $default_width: cx
  $default_height: cy
points:
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [70, -150]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        clone_outer:
          key:
            splay: 8
            asym: clone
            column_net: P017
          rows.mod.skip: true
        outer:
          key.splay: 0
          key.column_net: P020
          rows.mod:
            key.skip: true
            asym: source
        pinky:
          key.splay: -4
          key.column_net: P022
          rows.mod.skip: true
        ring:
          key.splay: -4
          key.column_net: P024
          key.stagger: 5
          rows.mod.skip: true
        middle:
          key.stagger: 2.5
          key.column_net: P100
          rows.mod.skip: true
        index:
          key.column_net: P011
          rows.mod.column_net: P100
          key.stagger: -2.5 
        inner:
          key.stagger: -2.5
          key.column_net: P104
          rows.mod.skip: true
      rows:
        mod:
          row_net: P115
        bottom:
          row_net: P002
        home:
          row_net: P029
        top:
          row_net: P031
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_inner_mod
        shift: [2, -2]
      columns:
        layer:
          key:
            column_net: P011
            splay: -15
            shift: [0, -0.5]
        space:
          key:
            column_net: P104
            splay: -15
            shift: [3, -3]
      rows:
        cluster:
          row_net: P115
  mirror: &mirror
    ref: matrix_inner_top
    distance: 5kx
outlines:
  raw:
    - what: rectangle
      where: true
      size: [kx, ky]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board_left:
    - what: polygon
      operation: stack
      points:
        - ref: thumbs_space_cluster
          shift: [0.5px, -0.5py]
        - ref: thumbs_space_cluster
          shift: [0.5px, 0.5py]
        - orient: 30
          shift: [0px,3py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: matrix_outer_top
          shift: [-0.5px,0.5py]
        - ref: matrix_outer_mod
          shift: [-0.5px,-0.5py]
        - ref: matrix_index_mod
          shift: [-0.5px, -0.5py]
      fillet: 3
  xl_board_left:
    - what: polygon
      operation: stack
      points:
        - ref: thumbs_space_cluster
          shift: [0.53dpx, -0.5dpy]
        - ref: thumbs_space_cluster
          shift: [0.52dpx, 0.48dpy]
        - orient: 30
          # manual intervention xD
          # 3py + 0.5 * 4 = 3 * (17 + 5) + 2 = 68 
          shift: [0,68]
        - ref: matrix_middle_top
          shift: [0.5dpx,0.52dpy]
        - ref: matrix_middle_top
          shift: [-0.5dpx,0.52dpy]
        - ref: matrix_ring_top
          shift: [-0.5dpx,0.5dpy]
        - ref: matrix_outer_top
          shift: [-0.52dpx,0.5dpy]
        - ref: matrix_outer_mod
          shift: [-0.52dpx,-0.52dpy]
        - ref: matrix_index_mod
          shift: [-0.4dpx, -0.54dpy]
      fillet: 3
  xs_board_left:
    - what: polygon
      operation: stack
      points:
        - ref: thumbs_space_cluster
          shift: [0.5spx, -0.5spy]
        - ref: thumbs_space_cluster
          shift: [0.5spx, 0.5spy]
        - orient: 30
          shift: [0px,2.96py]
        - ref: matrix_middle_top
          shift: [0.5spx,0.5spy]
        - ref: matrix_middle_top
          shift: [-0.5spx,0.5spy]
        - ref: matrix_ring_top
          shift: [-0.5spx,0.5spy]
        - ref: matrix_outer_top
          shift: [-0.5spx,0.5spy]
        - ref: matrix_outer_mod
          shift: [-0.5spx,-0.5spy]
        - ref: matrix_index_mod
          shift: [-0.5spx, -0.5spy]
      fillet: 3
  board_right:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_thumbs_space_cluster
          shift: [0.5px, -0.5py]
        - ref: mirror_thumbs_space_cluster
          shift: [0.5px, 0.5py]
        - orient: 30
          shift: [0px,3py]
        - ref: mirror_matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_clone_outer_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_clone_outer_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_matrix_index_mod
          shift: [-0.5px, -0.5py]
      fillet: 3
  xl_board_right:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_thumbs_space_cluster
          shift: [0.53dpx, -0.5dpy]
        - ref: mirror_thumbs_space_cluster
          shift: [0.52dpx, 0.48dpy]
        - orient: 30
          # manual intervention xD
          # 3py + 0.5 * 4 = 3 * (17 + 5) + 2 = 68 
          shift: [0,68]
        - ref: mirror_matrix_middle_top
          shift: [0.5dpx,0.52dpy]
        - ref: mirror_matrix_middle_top
          shift: [-0.5dpx,0.52dpy]
        - ref: mirror_matrix_ring_top
          shift: [-0.5dpx,0.5dpy]
        - ref: mirror_matrix_clone_outer_top
          shift: [-0.52dpx,0.5dpy]
        - ref: mirror_matrix_clone_outer_bottom
          shift: [-0.52dpx,-0.5dpy]
        - ref: mirror_matrix_index_mod
          shift: [-0.5dpx, -0.5dpy]
      fillet: 3
  xs_board_right:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_thumbs_space_cluster
          shift: [0.5spx, -0.5spy]
        - ref: mirror_thumbs_space_cluster
          shift: [0.5spx, 0.5spy]
        - orient: 30
          shift: [0px,3.25spy]
        - ref: mirror_matrix_middle_top
          shift: [0.5spx,0.5spy]
        - ref: mirror_matrix_middle_top
          shift: [-0.5spx,0.5spy]
        - ref: mirror_matrix_ring_top
          shift: [-0.5spx,0.5spy]
        - ref: mirror_matrix_clone_outer_top
          shift: [-0.5spx,0.5spy]
        - ref: mirror_matrix_clone_outer_bottom
          shift: [-0.5spx,-0.5spy]
        - ref: mirror_matrix_index_mod
          shift: [-0.5spx, -0.5spy]
      fillet: 3
  # Combo with keys
  combo_right:
    - name: board_right
    - operation: subtract
      name: keys
  combo_left:
    - name: board_left
    - operation: subtract
      name: keys

  # Combo for case walls 
  case_wall_left: 
    - name: xl_board_left
    - operation: subtract
      name: board_left
  case_wall_right: 
    - name: xl_board_right
    - operation: subtract
      name: board_right

  # Combo for inspecting stand next to wall
  inspect_wall_left: 
    - name: xl_board_left
    - operation: subtract
      name: board_left
    - operation: add
      name: xs_board_left
  inspect_wall_right: 
    - name: xl_board_right
    - operation: subtract
      name: board_right
    - operation: add
      name: xs_board_right

  combo:
    - name: combo_left
    - operation: add
      name: combo_right

  # The mounting outlines
  left_mounting: 
    - what: circle
      radius: screw_rad
      where:
        ref: [matrix_outer_top]
        shift: [0.5kx, -0.3ky]
    - what: circle
      radius: screw_rad
      where:
        ref: [matrix_inner_top]
        shift: [0.5kx, -0.3ky]
    - what: circle
      radius: screw_rad
      where:
        ref: [matrix_middle_home]
        shift: [0.5kx, -0.35ky]
    - what: circle
      radius: screw_rad
      where:
        ref: [matrix_outer_mod]
        shift: [0.5kx, -0.3ky]
    - what: circle
      radius: screw_rad
      where:
        ref: [thumbs_space_cluster]
        shift: [-0.5kx, -0.3ky]
  left_mounting_standoff: 
    - what: circle
      radius: screw_standoff_rad
      where:
        ref: [matrix_outer_top]
        shift: [0.5kx, -0.3ky]
    - what: circle
      radius: screw_standoff_rad
      where:
        ref: [matrix_inner_top]
        shift: [0.5kx, -0.3ky]
    - what: circle
      radius: screw_standoff_rad
      where:
        ref: [matrix_middle_home]
        shift: [0.5kx, -0.35ky]
    - what: circle
      radius: screw_standoff_rad
      where:
        ref: [matrix_outer_mod]
        shift: [0.5kx, -0.3ky]
    - what: circle
      radius: screw_standoff_rad
      where:
        ref: [thumbs_space_cluster]
        shift: [-0.5kx, -0.3ky]
  # right
  right_mounting:
    - what: circle
      radius: screw_rad
      where:
        ref: [mirror_matrix_clone_outer_top]
        shift: [0.5kx, -0.3ky]
    - what: circle
      radius: screw_rad
      where:
        ref: [mirror_matrix_inner_top]
        shift: [0.5kx, -0.3ky]
    - what: circle
      radius: screw_rad
      where:
        ref: [mirror_matrix_middle_home]
        shift: [0.5kx, -0.35ky]
    - what: circle
      radius: screw_rad
      where:
        ref: [mirror_matrix_clone_outer_bottom]
        shift: [0.5kx, -0.3ky]
    - what: circle
      radius: screw_rad
      where:
        ref: [mirror_thumbs_space_cluster]
        shift: [-0.5kx, -0.3ky]
  right_mounting_standoff: 
    - what: circle
      radius: screw_standoff_rad
      where:
        ref: [mirror_matrix_clone_outer_top]
        shift: [0.5kx, -0.3ky]
    - what: circle
      radius: screw_standoff_rad
      where:
        ref: [mirror_matrix_inner_top]
        shift: [0.5kx, -0.3ky]
    - what: circle
      radius: screw_standoff_rad
      where:
        ref: [mirror_matrix_middle_home]
        shift: [0.5kx, -0.35ky]
    - what: circle
      radius: screw_standoff_rad
      where:
        ref: [mirror_matrix_clone_outer_bottom]
        shift: [0.5kx, -0.3ky]
    - what: circle
      radius: screw_standoff_rad
      where:
        ref: [mirror_thumbs_space_cluster]
        shift: [-0.5kx, -0.3ky]
pcbs:
  # LEFT PCB
  left_pcb:
    outlines:
      main:
        outline: board_left
    footprints:
      choc_hotswap:
        what: choc
        where: -/^mirror.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: -/^mirror.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: matrix_inner_top
          shift: [23, -15]
          rotate: -90
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: matrix_inner_top
          shift: [23, 4]
          rotate: -90
        params:
            side: B
            pos: pos
            neg: GND
      battery_switch:
        what: slider
        where:
          ref: matrix_inner_top
          shift: [23, -34]
          rotate: -180
        params:
            side: F
            from: pos
            to: RAW
      # five mounting holes per pcb
      holeTopLeft:
        what: mountinghole
        where:
          ref: [matrix_outer_top]
          shift: [0.5kx, -0.3ky]
      holeTopRight:
        what: mountinghole
        where:
          ref: [matrix_inner_top]
          shift: [0.5kx, -0.3ky]
      holeMiddle:
        what: mountinghole
        where:
          ref: [matrix_middle_home]
          shift: [0.5kx, -0.35ky]
      holeBotLeft:
        what: mountinghole
        where:
          ref: [matrix_outer_mod]
          shift: [0.5kx, -0.3ky]
      holeBotRight:
        what: mountinghole
        where:
          ref: [thumbs_space_cluster]
          shift: [-0.5kx, -0.3ky]

  # RIGHT PCB
  right_pcb:
    outlines:
      main:
        outline: board_right
    footprints:
      choc_hotswap:
        what: choc
        where: /^mirror_.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^mirror_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: mirror_matrix_inner_top
          shift: [23, -15]
          rotate: 90
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: mirror_matrix_inner_top
          shift: [23, 4]
          rotate: -90
        params:
            side: 'B'
            pos: pos
            neg: GND
      battery_switch:
        what: slider
        where:
          ref: mirror_matrix_inner_top
          shift: [23, -34]
          rotate: -180
        params:
            side: F
            from: pos
            to: RAW
      # Five mounting holes per pcb
      holeTopRight:
        what: mountinghole
        where:
          ref: [mirror_matrix_clone_outer_top]
          shift: [0.5kx, -0.3ky]
      holeTopLeft:
        what: mountinghole
        where:
          ref: [mirror_matrix_inner_top]
          shift: [0.5kx, -0.3ky]
      holeMiddle:
        what: mountinghole
        where:
          ref: [mirror_matrix_middle_home]
          shift: [0.5kx, -0.35ky]
      holeBotRight:
        what: mountinghole
        where:
          ref: [mirror_matrix_clone_outer_bottom]
          shift: [0.5kx, -0.3ky]
      holeBotLeft:
        what: mountinghole
        where:
          ref: [mirror_thumbs_space_cluster]
          shift: [-0.5kx, -0.3ky]

cases:
  # Left case
  _xl_left_bottom:
    - name: xl_board_left
      extrude: case_bottom_thick
  _left_wall:
    - name: case_wall_left
      extrude: case_wall_height
  _left_mounting: 
    - name: left_mounting
      extrude: pcb_bottom_height
  _left_standoff: 
    - name: left_mounting_standoff
      extrude: pcb_bottom_height
  # next to wall standoff
  _left_next_to_wall_standoff_full: 
    - name: xs_board_left
      extrude: pcb_bottom_height 
  _xl_left_bottom_pcb_bot_h: 
    - name: xl_board_left
      extrude: pcb_bottom_height
  _left_next_to_wall_standoff: 
    - what: case
      name: _xl_left_bottom_pcb_bot_h
      operation: add
    - what: case
      name: _left_next_to_wall_standoff_full
      operation: subtract

  # Gather
  left_case:
    - what: case
      name: _left_wall
      operation: add
    - what: case
      name: _left_standoff
      operation: add
    - what: case
      name: _left_mounting
      operation: subtract
    - what: case
      name: _xl_left_bottom
      operation: add
    - what: case
      name: _left_next_to_wall_standoff
      operation: add

  # Right case
  _xl_right_bottom:
    - name: xl_board_right
      extrude: case_bottom_thick
  _right_wall:
    - name: case_wall_right
      extrude: case_wall_height
  _right_mounting: 
    - name: right_mounting
      extrude: pcb_bottom_height
  _right_standoff: 
    - name: right_mounting_standoff
      extrude: pcb_bottom_height
  # next to wall standoff
  _right_next_to_wall_standoff_full: 
    - name: xs_board_right
      extrude: pcb_bottom_height 
  _xl_right_bottom_pcb_bot_h: 
    - name: xl_board_right
      extrude: pcb_bottom_height
  _right_next_to_wall_standoff: 
    - what: case
      name: _xl_right_bottom_pcb_bot_h
      operation: add
    - what: case
      name: _right_next_to_wall_standoff_full
      operation: subtract

  # Gather
  right_case:
    - what: case
      name: _right_wall
      operation: add
    - what: case
      name: _right_standoff
      operation: add
    - what: case
      name: _right_mounting
      operation: subtract
    - what: case
      name: _xl_right_bottom
      operation: add
    - what: case
      name: _right_next_to_wall_standoff
      operation: add
